### ISSUE TITLE
pdf 都是方块乱码，系统是 macOS 11.5.2

### ISSUE THREAD

**Issue by zchtcl** [MwumLi/book-refactoring2#1]

**Comment by raymond-liao** [comment]
windows 也是

**Comment by jianbojason** [comment]
怎么解决？这个方块的问题

**Comment by jp311** [comment]
应该是没有字体吧

Fonts: 
DejaVuSans (TrueType (CID); Identity-H; embedded)
DejaVuSans-Bold (TrueType (CID); Identity-H; embedded)
DejaVuSansMono (TrueType (CID); Identity-H; embedded)
LiberationMono (TrueType (CID); Identity-H; embedded)
LiberationSans (TrueType (CID); Identity-H; embedded)
LiberationSans-Bold (TrueType (CID); Identity-H; embedded)

**Comment by MwumLi** [comment]
可能是中文字体缺失的问题

**Comment by MwumLi** [comment]
才发现，这个项目 CI 构建自动生成的 PDF 也乱码了，你们谁有解决方案吗？

**Comment by MwumLi** [comment]
可以了，最新的 PDF 可以在线文档首页下载  
![image](https://user-images.githubusercontent.com/6889433/219853965-07c83913-86c8-4a64-b7a2-6d8fd039d180.png)

我已经在此项目 CI 解决了，主要是缺乏中文字体，具体见 
https://github.com/MwumLi/book-refactoring2/blob/8198f0008c83354e22e1101c7b35b4d75b6f9aaf/.github/workflows/gh-pages.yml#L25-L26

**Comment by MwumLi** [comment]
> windows 也是

重新拉取试试，增加了这个
https://github.com/MwumLi/book-refactoring2/blob/75397b53c6ffc072c44c303e1847af9a947a177d/book.json#L18

Arial Unicode MS 是一种 TrueType 字体，它是 Microsoft 公司专门为 Unicode 编码而设计的字体，支持包括汉字在内的各种字符集，具有较好的跨平台兼容性。因此，Arial Unicode MS 字体可以用于显示不同语言的文本，并且适合用于数字文档，例如 PDF 文件。

对于中文乱码问题，常常是因为文本的编码格式与所使用的字体不匹配所导致的。Arial Unicode MS 字体支持 Unicode 编码，可以正确地显示包括中文在内的各种字符，因此在 Gitbook 的 PDF 配置指定字体为 Arial Unicode MS，可以解决中文乱码问题。
